name: continuous (Preview) releases
on:
  pull_request_review:
    types: [submitted]
  pull_request: 
    types: [labeled, synchronize]

jobs:
  approved:
    if: github.event.review.state == 'APPROVED' && !contains(github.event.pull_request.labels.*.name, 'DO NOT PREVIEW RELEASE') || contains(github.event.pull_request.labels.*.name, 'Bypass check - PREVIEW RELEASE') || (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'PR Manual CI RUN'))
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install pkg-pr-new & prebuild, dependencies
        run: npm install pkg-pr-new --save-dev --no-frozen-lockfile

      - run: npx pkg-pr-new publish

      - name: Remove Manual PR Run label
        if: github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'PR Manual CI RUN')
        run: gh pr edit $PR --remove-label $labels
        env:
          PR: ${{ github.event.pull_request.number }}
          labels: 'PR Manual CI RUN'
